In [1]:
# import python's module
import pandas as pd
import json

# load data
log_df = pd.read_csv("operation-log.csv")  
log_df
# _df stands for data frame. It is a common suffix to indicate variable type.

,date,operator,location,operation,note,Power Unit,Seeds planted,Seeding Rate (seeds/ac),Fertilizers applied,Fertilizer Rate (lb/ac)
0,4/24/2022,Evan,200,Spread/Spray,2-4D round up burn down,Hagie STS12,NaN,NaN,NaN,NaN
1,4/27/2022,Bryan,6,Spread/Spray,"20oz ru, 11 24d",Hagie STS12,NaN,NaN,NaN,NaN
2,4/27/2022,Bryan,5,Spread/Spray,20 oz ru/ 11 oz 24d,Hagie STS12,NaN,NaN,NaN,NaN
3,4/27/2022,Bryan,Cotton,Spread/Spray,20 oz ru. 11 oz 24d,Hagie STS12,NaN,NaN,NaN,NaN
4,4/27/2022,Bryan,101,Spread/Spray,20 oz ru 11 oz 24d,Hagie STS12,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
428,11/17/2022,Ceres,105,Spread/Spray,VRF MAP: 153 lbs/ac\nVRF Potash: 133 lbs/ac,NaN,NaN,NaN,"MAP,Potash (0-0-60)",NaN
429,11/17/2022,Ceres,111,Spread/Spray,VRF MAP: 139 lbs/ac\nVRF Potash: 121 lbs/ac,NaN,NaN,NaN,"MAP,Potash (0-0-60)",NaN
430,11/17/2022,Ceres,33,Spread/Spray,VRF MAP: 154 lbs/ac,NaN,NaN,NaN,MAP,NaN
431,11/17/2022,Ceres,41,Spread/Spray,VRF MAP: 115.8 lbs/ac,NaN,NaN,NaN,MAP,NaN
432,11/17/2022,Ceres,5,Spread/Spray,MAP: 240 lbs/ac\nPotash: 225 lbs/ac,NaN,NaN,NaN,"MAP,Potash (0-0-60)",NaN

In [16]:
# create a list which we will add dictionaries later
user = [] # suffix s is common way to indicate a list (array)
# ! check this DK
for operator in log_df['operator'].unique(): # we iterate over the result from unique function
    user.append( # append new element to the list
        { # curly bracket indicate the starting of dictionary
            "operator": operator, # each key-value pair
        } # the end of dictionary
    )
operator_df = pd.DataFrame(user)
operator_df.to_dict()
operator_df.to_dict()['operator']
index_name = operator_df.to_dict()['operator']
name2pk = dict((v, k+1) for k, v in index_name.items())

log_df['operator'] = log_df['operator'].map(name2pk)

In [23]:
# create a list which we will add dictionaries later
field = [] # suffix s is common way to indicate a list (array)
# ! check this DK
for location in log_df['location'].unique(): # we iterate over the result from unique function
    field.append( # append new element to the list
        { # curly bracket indicate the starting of dictionary
            "location": location, # each key-value pair
        } # the end of dictionary
    )
location_df = pd.DataFrame(field)
location_df.to_dict()
location_df.to_dict()['location']
index_name = location_df.to_dict()['location']
name2pk = dict((v, k+1) for k, v in index_name.items())
print(name2pk)
log_df['location'] = log_df['location'].map(name2pk)

{'200': 1, '6': 2, '5': 3, 'Cotton': 4, '101': 5, '61': 6, '62': 7, '70S': 8, '63': 9, '54N': 10, '83': 11, '65': 12, '68': 13, '56': 14, '52': 15, '51': 16, '117': 17, '107': 18, '95': 19, '64': 20, '23': 21, '3': 22, '4': 23, 'The Teens': 24, '72': 25, '82': 26, '54S': 27, '111': 28, '55S': 29, '55C': 30, '85': 31, '59': 32, '58': 33, '57': 34, '115': 35, '116': 36, '118': 37, '106': 38, '34': 39, '86': 40, '96E': 41, '42': 42, '41': 43, '91': 44, '92': 45, '96W': 46, '108': 47, '33': 48, '71': 49, '110': 50, '10D': 51, '70N': 52, 'Trail Iso.': 53, '74': 54, '75': 55, '76': 56, '93': 57, '94': 58, '15': 59, '84': 60, '24': 61, '10C': 62, '103': 63, 'LTT': 64, '105': 65, 'McKinnis': 66, '102': 67, '104N': 68, '104': 69, '32': 70, '67': 71, '78': 72, '77': 73, '66': 74, '69': 75, '131': 76, '22B': 77, 'WQFS': 78, '43': 79, '73': 80, '44': 81, '9D': 82, '9CN': 83, '81': 84, '55N': 85, '21A': 86, '22C': 87, '22D': 88, '22E': 89, '9CS': 90, '22A': 91, '53': 92}

In [ ]:
# create a list which we will add dictionaries later
event = [] # suffix s is common way to indicate a list (array)
# ! check this DK
for operation in log_df['operation'].unique(): # we iterate over the result from unique function
    event.append( # append new element to the list
        { # curly bracket indicate the starting of dictionary
            "operation": operation, # each key-value pair
        } # the end of dictionary
    )
event_df = pd.DataFrame(event)
event_df
event_df.to_dict()
event_df.to_dict()['operation']
index_name = event_df.to_dict()['operation']
name2pk = dict((v, k+1) for k, v in index_name.items())

log_df['operation'] = log_df['operation'].map(name2pk) 
pd.to_datetime(log_df['date'])
log_df['date'] = pd.to_datetime(log_df['date']).dt.strftime('%Y-%m-%d')

In [24]:
log = []
for index, row in log_df.iterrows(): # we iterate over the dataframe row by row
    log.append( # append new element to the list
        { # curly bracket indicate the starting of dictionary
            "model": "acrelog.log",  # the class name
            "pk": index+1, # index starts at 0 while primary key starts at 1. 
            "fields": { # this is a dictionary of attributes
                "location": row['location'],
                "event": row['operation'],
                "operator": row['operator'],
                "date": row['date'],
                "note": row['note'],
            }
        } # the end of dictionary
    )

json.dumps(log)
# or write the JSON to the file directly 
with open('log-data.json', 'w') as fp:
    json.dump(log, fp=fp, indent=4)